# Numpy数据基础

In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.4'

In [3]:
import array

In [4]:
arr = array.array("i", [i for i in range(10)])

In [5]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr[5] = 100

In [7]:
arr

array('i', [0, 1, 2, 3, 4, 100, 6, 7, 8, 9])

In [8]:
nparr = np.array([i for i in range(10)])

In [9]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
nparr[5]

5

In [11]:
nparr[5] = 100

In [12]:
nparr.dtype

dtype('int64')

In [13]:
nparr[5] = 5.0

In [14]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
nparr[3] = 3.14

In [16]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
nparr2 = np.array([1, 2, 3.0])

In [18]:
nparr2.dtype

dtype('float64')

In [19]:
nparr2[1] = 3.14159

In [20]:
nparr2

array([1.     , 3.14159, 3.     ])