# 其他创建 Numpy的方法

In [1]:
import numpy as np

In [2]:
np.zeros(10)  # 默认浮点数

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10).dtype

dtype('float64')

In [4]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.full(shape=(3,5), fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

## arrange

In [9]:
np.arange(0,20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.arange(0, 1, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace

In [12]:
np.linspace(0, 20, 10) # 包含首尾

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [13]:
np.linspace(0, 20, 11)


array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

## random

In [14]:
np.random.randint(0, 10)

6

In [15]:
np.random.randint(0, 10, 10) #生成10个0-10的随机数

array([8, 6, 4, 6, 4, 2, 0, 9, 8, 5])

In [16]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.random.randint(low=4, high=8, size=10)

array([4, 4, 5, 7, 4, 5, 4, 6, 6, 5])

In [18]:
np.random.randint(4, 8, size=(3, 5))

array([[7, 5, 6, 5, 6],
       [4, 7, 6, 5, 4],
       [5, 7, 4, 6, 7]])

In [19]:
np.random.randint(4, 8, size=(3, 5)) 

array([[4, 5, 5, 4, 5],
       [5, 6, 4, 6, 4],
       [7, 4, 5, 7, 7]])

In [20]:
np.random.seed(666) # 设置一个随机数的种子

In [21]:
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [22]:
np.random.seed(666)
np.random.randint(4, 8, size=(3, 5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [23]:
np.random.random() # 生成1个随机浮点数

0.2811684913927954

In [24]:
np.random.random(10)  # 生成10个随机浮点数

array([0.46284169, 0.23340091, 0.76706421, 0.81995656, 0.39747625,
       0.31644109, 0.15551206, 0.73460987, 0.73159555, 0.8578588 ])

In [25]:
np.random.normal() #生成一个均值为0，方差为1

0.7833709215884975

In [26]:
np.random.normal(10, 100)  # 设置均值为10，方差100

-37.08266661180856

In [27]:
np.random.normal(0, 10, (3,5))

array([[  6.13609815,  -2.17476384,   2.21969619, -18.67351825,
         -2.55847593],
       [-17.64380833,  -9.42496882, -15.80458612,   9.04726618,
         -8.26283265],
       [  8.21013692,   3.67125916,  16.53995858,   1.39464726,
        -12.1715355 ]])