# Numpy中的聚合运算

In [1]:
import numpy as np

In [2]:
L = np.random.random(100)
L

array([0.49396133, 0.63490073, 0.79384369, 0.7483168 , 0.00857494,
       0.37117704, 0.90502379, 0.78641203, 0.80547936, 0.30928581,
       0.47243612, 0.69276524, 0.62000384, 0.29735299, 0.86398918,
       0.40959369, 0.51850297, 0.57874607, 0.59812176, 0.36502174,
       0.5518209 , 0.77064152, 0.06917963, 0.0594742 , 0.96562238,
       0.79634455, 0.46628316, 0.27909878, 0.80978668, 0.07418895,
       0.44451548, 0.42500652, 0.42458819, 0.71919631, 0.14877802,
       0.49554302, 0.4621136 , 0.82350933, 0.3019795 , 0.83098275,
       0.2415645 , 0.4532888 , 0.96063054, 0.15376291, 0.84085354,
       0.95149964, 0.11079136, 0.66721183, 0.25728492, 0.10675117,
       0.6039222 , 0.33922554, 0.86982572, 0.04942336, 0.28792437,
       0.29914237, 0.16751099, 0.28453078, 0.21650023, 0.2554496 ,
       0.91553483, 0.63317856, 0.69296365, 0.19789074, 0.24791707,
       0.18106954, 0.55862129, 0.45307945, 0.99511225, 0.51411298,
       0.71806289, 0.52734117, 0.13643788, 0.06182409, 0.27907

In [3]:
sum(L)

49.993022302241094

In [4]:
np.sum(L)

49.99302230224109

In [5]:
big_array = np.random.random(1000000)
%time sum(big_array)
%time np.sum(big_array)
%time big_array.sum()

CPU times: user 110 ms, sys: 1.87 ms, total: 112 ms
Wall time: 115 ms
CPU times: user 1.57 ms, sys: 175 µs, total: 1.74 ms
Wall time: 1.1 ms
CPU times: user 1.68 ms, sys: 269 µs, total: 1.95 ms
Wall time: 1.21 ms


499589.8135449111

In [6]:
np.max(big_array)

0.99999830769561

In [7]:
np.min(big_array)

8.690065275152037e-07

In [8]:
big_array.max()

0.99999830769561

In [9]:
big_array.min()

8.690065275152037e-07

In [10]:
X = np.arange(16).reshape(4, -1)
X


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.sum(X)

120

In [12]:
np.sum(X, axis=0) # 列加

array([24, 28, 32, 36])

In [13]:
np.sum(X, axis=1) # 行加

array([ 6, 22, 38, 54])

In [14]:
np.prod(X)

0

In [15]:
np.prod(X, axis=0)

array([   0,  585, 1680, 3465])

In [16]:
np.prod(X, axis=1)

array([    0,   840,  7920, 32760])

In [17]:
np.mean(X) # 平均数

7.5

In [18]:
np.median(X)  # 中位数

7.5

In [19]:
v = np.array([1, 1, 2, 2, 10])
np.mean(v)

3.2

In [20]:
np.median(v)

2.0

In [22]:
np.percentile(big_array, q=50)  # 50%

0.49978562664343074

In [23]:
np.percentile(big_array, q = 100)

0.99999830769561

In [25]:
np.max(big_array)

0.99999830769561

In [26]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array, q = percent))

8.690065275152037e-07
0.24932478945745506
0.49978562664343074
0.7496323761596072
0.99999830769561


In [27]:
np.var(big_array) # 求方差

0.08340896903728746

In [28]:
np.std(big_array) # 求标准差

0.28880610976447063

In [30]:
x = np.random.normal(0, 1, size=100000)
x

array([ 1.53702627,  1.60616777,  0.55366593, ..., -0.09435894,
       -1.23531044,  0.39258589])

In [31]:
np.mean(x)

0.0018607413278660635

In [32]:
np.std(x)

0.9978578704769601