# 索引

In [1]:
import numpy as np

In [2]:
x = np.random.normal(0, 1, size=100000)
x

array([ 1.20951369, -0.33005955, -0.8885526 , ..., -0.27917097,
       -1.20298929,  0.36969418])

In [3]:
np.min(x)

-4.460091228298464

In [4]:
np.argmin(x)

40683

In [5]:
x[40683]

-4.460091228298464

In [6]:
np.argmax(x)

66568

In [7]:
x[66568]

5.0926427998853265

In [9]:
np.max(x)

5.0926427998853265

### 排序和使用索引

In [11]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [13]:
np.random.shuffle(x)
x

array([ 0, 12,  1, 14,  2,  3,  6, 13, 15,  7,  5,  9, 11,  8, 10,  4])

In [15]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
X = np.random.randint(10 ,size=(4,4))
X

array([[5, 9, 6, 6],
       [4, 3, 6, 6],
       [0, 9, 6, 1],
       [5, 9, 3, 7]])

In [20]:
np.sort(X) # 对每一行进行排序

array([[5, 6, 6, 9],
       [3, 4, 6, 6],
       [0, 1, 6, 9],
       [3, 5, 7, 9]])

In [23]:
np.sort(X, axis=0) # 对沿着行大方向进行排序，每列有序

array([[0, 3, 3, 1],
       [4, 9, 6, 6],
       [5, 9, 6, 6],
       [5, 9, 6, 7]])

In [26]:
np.random.shuffle(x)
x

array([ 1, 15,  2, 12, 11,  5,  6, 10, 14,  8,  7,  4, 13,  0,  3,  9])

In [28]:
np.argsort(x) # 排序好存放元素的索引

array([13,  0,  2, 14, 11,  5,  6, 10,  9, 15,  7,  4,  3, 12,  8,  1])

In [30]:
np.partition(x, 3) # 以3为分界点，3前面的元素都比3小，后面都比3大

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 14, 15, 13, 11, 12, 10])

In [31]:
np.argpartition(x, 3)

array([13,  0,  2, 14, 11,  5,  6, 10,  9, 15,  8,  1, 12,  4,  3,  7])

In [32]:
x

array([ 1, 15,  2, 12, 11,  5,  6, 10, 14,  8,  7,  4, 13,  0,  3,  9])

In [33]:
X

array([[5, 9, 6, 6],
       [4, 3, 6, 6],
       [0, 9, 6, 1],
       [5, 9, 3, 7]])

In [34]:
np.argsort(X, axis=1) # 按行进行排序

array([[0, 2, 3, 1],
       [1, 0, 2, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1]])

In [35]:
np.argpartition(X, 2, axis=1)

array([[0, 2, 3, 1],
       [1, 0, 2, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1]])