# Numpy中的比较和Fancyindex

In [1]:
import numpy as np
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
x[3]

3

In [5]:
x[3:9]

array([3, 4, 5, 6, 7, 8])

In [6]:
x[3:9:2]

array([3, 5, 7])

In [10]:
ind = [3, 5, 8]  # 访问指定index的值
x[ind]

array([3, 5, 8])

In [11]:
ind = np.array([[0,2], [1,3]]) # 二维数组使用
x[ind]

array([[0, 2],
       [1, 3]])

In [14]:
X = x.reshape(4, -1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
row = np.array([0,1,2])
row

array([0, 1, 2])

In [18]:
col = np.array([1,2,3])
col

array([1, 2, 3])

In [20]:
X[row, col] 

array([ 1,  6, 11])

In [21]:
col = [True, False, True, True]
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

In [22]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Numpy.array的比较

In [24]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [26]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [27]:
x <= 3

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [28]:
x >= 3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [29]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [30]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [31]:
2 * x == 24 -4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [32]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [34]:
np.sum(x <= 3)

4

In [36]:
np.count_nonzero(x <= 3)

4

In [37]:
np.any(x == 0)

True

In [38]:
np.any(x<0)

False

In [39]:
np.all(x >= 0)

True

In [40]:
np.all(x>0)

False

In [41]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
np.sum(X%2==0)

8

In [46]:
np.sum(X%2==0, axis=1)

array([2, 2, 2, 2])

In [47]:
np.sum(X%2==0, axis=0)

array([4, 0, 4, 0])

In [50]:
np.all(X > 0, axis=1)

array([False,  True,  True,  True])

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
np.sum((x > 3) & (x < 10))

6

In [55]:
np.sum((x%2==0)|(x>10))

11

In [56]:
np.sum(~(x==0))

15

In [57]:
x[x<5]

array([0, 1, 2, 3, 4])

In [58]:
x[x%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [60]:
X[X[:,3] % 3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])