# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexs = np.random.permutation(len(X))
shuffle_indexs

array([ 39,   7,  81, 115,   2,   9,  65,  52, 130,  10,  26, 128,  62,
       125, 117,  31, 127, 133,  55, 103,  78,  69, 139,  56, 140,   6,
       118,  87,  18, 100,  61,  15, 142,  37,  28, 114, 138, 121,   0,
        12, 148,  82, 146,  76, 110, 131,   1,   4,  88,  53, 134,  71,
        27,  97, 101,  33,  92,  51,  19, 102,  58, 123,  42, 119,  35,
        44,  93, 124,  99,  74,  21,  96,  59, 141,  46,  22,  91, 112,
        95, 109,  77, 136, 106, 132,  24,  80,  25, 129,   5, 143,  32,
        66,  86,  11,  63,  57,  13, 105,  50, 108,  23,  94,  41,  83,
       113,  60, 147,  16,  89,   8, 116,  36,   3, 149, 111, 104, 145,
       137,  20,  72,  43,  68,  45,  79,  73,  47,  49,  70,  67,  98,
       135, 120, 107,  54, 126,  14,  29,  17,  34,  30,  85,  48,  64,
        40, 144,  75, 122,  84,  38,  90])

In [8]:
test_ratio = 0.2
test_size = int(len(X)*test_ratio)
test_size

30

In [9]:
test_indexes = shuffle_indexs[:test_size]
test_indexes

array([ 39,   7,  81, 115,   2,   9,  65,  52, 130,  10,  26, 128,  62,
       125, 117,  31, 127, 133,  55, 103,  78,  69, 139,  56, 140,   6,
       118,  87,  18, 100])

In [10]:
train_indexes = shuffle_indexs[test_size:]
train_indexes

array([ 61,  15, 142,  37,  28, 114, 138, 121,   0,  12, 148,  82, 146,
        76, 110, 131,   1,   4,  88,  53, 134,  71,  27,  97, 101,  33,
        92,  51,  19, 102,  58, 123,  42, 119,  35,  44,  93, 124,  99,
        74,  21,  96,  59, 141,  46,  22,  91, 112,  95, 109,  77, 136,
       106, 132,  24,  80,  25, 129,   5, 143,  32,  66,  86,  11,  63,
        57,  13, 105,  50, 108,  23,  94,  41,  83, 113,  60, 147,  16,
        89,   8, 116,  36,   3, 149, 111, 104, 145, 137,  20,  72,  43,
        68,  45,  79,  73,  47,  49,  70,  67,  98, 135, 120, 107,  54,
       126,  14,  29,  17,  34,  30,  85,  48,  64,  40, 144,  75, 122,
        84,  38,  90])

In [11]:
X_train = X[train_indexes]
X_train

array([[5.9, 3. , 4.2, 1.5],
       [5.7, 4.4, 1.5, 0.4],
       [5.8, 2.7, 5.1, 1.9],
       [4.9, 3.6, 1.4, 0.1],
       [5.2, 3.4, 1.4, 0.2],
       [5.8, 2.8, 5.1, 2.4],
       [6. , 3. , 4.8, 1.8],
       [5.6, 2.8, 4.9, 2. ],
       [5.1, 3.5, 1.4, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [6.2, 3.4, 5.4, 2.3],
       [5.8, 2.7, 3.9, 1.2],
       [6.3, 2.5, 5. , 1.9],
       [6.8, 2.8, 4.8, 1.4],
       [6.5, 3.2, 5.1, 2. ],
       [7.9, 3.8, 6.4, 2. ],
       [4.9, 3. , 1.4, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.3, 4. , 1.3],
       [6.1, 2.6, 5.6, 1.4],
       [6.1, 2.8, 4. , 1.3],
       [5.2, 3.5, 1.5, 0.2],
       [6.2, 2.9, 4.3, 1.3],
       [5.8, 2.7, 5.1, 1.9],
       [5.5, 4.2, 1.4, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [6.4, 3.2, 4.5, 1.5],
       [5.1, 3.8, 1.5, 0.3],
       [7.1, 3. , 5.9, 2.1],
       [6.6, 2.9, 4.6, 1.3],
       [6.3, 2.7, 4.9, 1.8],
       [4.4, 3.2, 1.3, 0.2],
       [6. , 2.2, 5. , 1.5],
       [5. , 3

In [12]:
y_train = y[train_indexes]
y_train

array([1, 0, 2, 0, 0, 2, 2, 2, 0, 0, 2, 1, 2, 1, 2, 2, 0, 0, 1, 1, 2, 1,
       0, 1, 2, 0, 1, 1, 0, 2, 1, 2, 0, 2, 0, 0, 1, 2, 1, 1, 0, 1, 1, 2,
       0, 0, 1, 2, 1, 2, 1, 2, 2, 2, 0, 1, 0, 2, 0, 2, 0, 1, 1, 0, 1, 1,
       0, 2, 1, 2, 0, 1, 0, 1, 2, 1, 2, 0, 1, 0, 2, 0, 0, 2, 2, 2, 2, 2,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 2, 2, 2, 1, 2, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 2, 1, 2, 1, 0, 1])

In [13]:
X_test = X[test_indexes]
y_test = y[test_indexes]

In [14]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


### 测试自己写的方法

In [15]:
from playML.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [18]:
from playML.kNN import KNNClassifier

In [19]:
my_knn_clf = KNNClassifier(k=3)
my_knn_clf

KNN(k=3)

In [20]:
my_knn_clf.fit(X_train, y_train)
my_knn_clf

KNN(k=3)

In [21]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([0, 1, 2, 2, 1, 2, 2, 1, 0, 1, 2, 2, 1, 0, 0, 1, 2, 1, 1, 0, 2, 2,
       1, 1, 1, 1, 2, 2, 2, 0])

In [22]:
y_test

array([0, 2, 2, 2, 1, 2, 2, 1, 0, 1, 2, 2, 1, 0, 0, 1, 2, 1, 1, 0, 2, 2,
       1, 1, 1, 1, 2, 2, 2, 0])

In [23]:
sum(y_predict == y_test)/len(y_test)  # 预测准确率

0.9666666666666667

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [26]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


### 调用sklearn中的算法

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
my_knn_clf = KNeighborsClassifier(n_neighbors=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [29]:
sum(y_predict == y_test)/len(y_test)

1.0