# 测试我们的算法

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y.shape

(150,)

In [6]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
shuffle_indexs = np.random.permutation(len(X))
shuffle_indexs

array([124,  70,  63, 138,  40,  45,   1, 109,  74, 118,  57,  14,   8,
        73, 117,  32,   0,  36, 110, 129,  95, 114,  54,  83,  92,  75,
       134,  47,  21, 102,  82,  93,  98,  26,  42,  52,  78,  46, 148,
       128,  79,  56,  29, 137,  97,   5, 106,  80,  87,  49,  64,  89,
       125,  37,   2,  99,  35,  39, 120,  18,  58, 130,   9,  96,  27,
       103, 115, 105, 131,  60,  86,  68, 141,  11,  13,  22,  30,  17,
        55, 123, 104,  50, 144,  41, 136,  94,  84,  15,  38,  16, 145,
       135, 149,  65,  24,  25,  43, 143,  12, 146, 100,  61,  69,   6,
       112,  67,  20,  72, 107, 101,   7, 127,  88,  51,   4,  34, 111,
       119,  62, 116,  10,  59,  23, 133,  28,  81, 121,  66, 122, 132,
        91,  53, 139,  76, 142,  77, 147, 113,  33, 126,  31,  90,  71,
       140,  85,  44,  48,  19,   3, 108])

In [8]:
test_ratio = 0.2
test_size = int(len(X)*test_ratio)
test_size

30

In [9]:
test_indexes = shuffle_indexs[:test_size]
test_indexes

array([124,  70,  63, 138,  40,  45,   1, 109,  74, 118,  57,  14,   8,
        73, 117,  32,   0,  36, 110, 129,  95, 114,  54,  83,  92,  75,
       134,  47,  21, 102])

In [10]:
train_indexes = shuffle_indexs[test_size:]
train_indexes

array([ 82,  93,  98,  26,  42,  52,  78,  46, 148, 128,  79,  56,  29,
       137,  97,   5, 106,  80,  87,  49,  64,  89, 125,  37,   2,  99,
        35,  39, 120,  18,  58, 130,   9,  96,  27, 103, 115, 105, 131,
        60,  86,  68, 141,  11,  13,  22,  30,  17,  55, 123, 104,  50,
       144,  41, 136,  94,  84,  15,  38,  16, 145, 135, 149,  65,  24,
        25,  43, 143,  12, 146, 100,  61,  69,   6, 112,  67,  20,  72,
       107, 101,   7, 127,  88,  51,   4,  34, 111, 119,  62, 116,  10,
        59,  23, 133,  28,  81, 121,  66, 122, 132,  91,  53, 139,  76,
       142,  77, 147, 113,  33, 126,  31,  90,  71, 140,  85,  44,  48,
        19,   3, 108])

In [11]:
X_train = X[train_indexes]
X_train

array([[5.8, 2.7, 3.9, 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.1, 2.5, 3. , 1.1],
       [5. , 3.4, 1.6, 0.4],
       [4.4, 3.2, 1.3, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [6. , 2.9, 4.5, 1.5],
       [5.1, 3.8, 1.6, 0.2],
       [6.2, 3.4, 5.4, 2.3],
       [6.4, 2.8, 5.6, 2.1],
       [5.7, 2.6, 3.5, 1. ],
       [6.3, 3.3, 4.7, 1.6],
       [4.7, 3.2, 1.6, 0.2],
       [6.4, 3.1, 5.5, 1.8],
       [6.2, 2.9, 4.3, 1.3],
       [5.4, 3.9, 1.7, 0.4],
       [4.9, 2.5, 4.5, 1.7],
       [5.5, 2.4, 3.8, 1.1],
       [6.3, 2.3, 4.4, 1.3],
       [5. , 3.3, 1.4, 0.2],
       [5.6, 2.9, 3.6, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [7.2, 3.2, 6. , 1.8],
       [4.9, 3.6, 1.4, 0.1],
       [4.7, 3.2, 1.3, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [5. , 3.2, 1.2, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [6.9, 3.2, 5.7, 2.3],
       [5.7, 3.8, 1.7, 0.3],
       [6.6, 2.9, 4.6, 1.3],
       [7.4, 2.8, 6.1, 1.9],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.9, 4.2, 1.3],
       [5.2, 3

In [12]:
y_train = y[train_indexes]
y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 1, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1,
       2, 0, 0, 1, 0, 0, 2, 0, 1, 2, 0, 1, 0, 2, 2, 2, 2, 1, 1, 1, 2, 0,
       0, 0, 0, 0, 1, 2, 2, 1, 2, 0, 2, 1, 1, 0, 0, 0, 2, 2, 2, 1, 0, 0,
       0, 2, 0, 2, 2, 1, 1, 0, 2, 1, 0, 1, 2, 2, 0, 2, 1, 1, 0, 0, 2, 2,
       1, 2, 0, 1, 0, 2, 0, 1, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 0, 2,
       0, 1, 1, 2, 1, 0, 0, 0, 0, 2])

In [13]:
X_test = X[test_indexes]
y_test = y[test_indexes]

In [14]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


### 测试自己写的方法

In [15]:
from playML.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [16]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [18]:
from playML.kNN import KNNClassifier

In [19]:
my_knn_clf = KNNClassifier(k=3)
my_knn_clf

KNN(k=3)

In [20]:
my_knn_clf.fit(X_train, y_train)
my_knn_clf

KNN(k=3)

In [21]:
y_predict = my_knn_clf.predict(X_test)
y_predict

array([1, 2, 1, 0, 1, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 1,
       1, 1, 0, 2, 1, 0, 0, 0])

In [22]:
y_test

array([2, 2, 1, 0, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 1, 0, 2, 2, 2, 0, 1, 2,
       1, 1, 0, 2, 1, 0, 0, 0])

In [23]:
sum(y_predict == y_test)/len(y_test)  # 预测准确率

0.9

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [26]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(120, 4)
(120,)
(30, 4)
(30,)


### 调用sklearn中的算法

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
my_knn_clf = KNeighborsClassifier(n_neighbors=3)
my_knn_clf.fit(X_train, y_train)
y_predict = my_knn_clf.predict(X_test)

In [29]:
sum(y_predict == y_test)/len(y_test)

1.0

In [30]:
y_train

array([0, 0, 1, 2, 1, 1, 2, 2, 0, 1, 2, 2, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2,
       1, 1, 1, 0, 0, 2, 2, 1, 2, 0, 1, 1, 0, 1, 0, 0, 2, 2, 2, 1, 1, 2,
       2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 2, 1,
       2, 2, 2, 2, 0, 2, 2, 1, 1, 2, 2, 1, 2, 1, 0, 2, 0, 1, 1, 2, 0, 2,
       2, 0, 2, 2, 1, 0, 0, 2, 0, 0, 0, 1, 0, 2, 1, 2, 0, 0, 0, 2, 2, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 2])